# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YFOCTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'AFNetworking', '4.0.1'
	pod 'SDWebImage', '5.8.4'
	pod 'MJRefresh', '3.4.3'
	pod 'MJExtension', ’3.2.2‘
	pod 'Masonry', '~> 1.1.0'
	pod 'YYText', '~> 1.0.7'
  
    pod 'TXLiteAVSDK_Professional', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_Professional.podspec'

  

  

end
